// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.petclinic;

import com.springsource.petclinic.T1;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect T1_Roo_Configurable {
    
    declare @type: T1: @Configurable;
    
}
