// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.petclinic;

import com.springsource.petclinic.T2;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect T2_Roo_Configurable {
    
    declare @type: T2: @Configurable;
    
}
