// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.springframework.roo.petclinic.repository;

import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Ignore;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.roo.petclinic.dod.OwnerDataOnDemand;
import org.springframework.roo.petclinic.repository.OwnerRepository;
import org.springframework.roo.petclinic.repository.OwnerRepositoryIT;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.test.context.web.WebAppConfiguration;

privileged aspect OwnerRepositoryIT_Roo_IT {
    
    declare @type: OwnerRepositoryIT: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: OwnerRepositoryIT: @ActiveProfiles("dev");
    
    declare @type: OwnerRepositoryIT: @WebAppConfiguration;
    
    declare @type: OwnerRepositoryIT: @SpringBootTest;
    
    /**
     * TODO Auto-generated attribute documentation
     */
    OwnerDataOnDemand OwnerRepositoryIT.dod;
    
    /**
     * TODO Auto-generated attribute documentation
     */
    @Autowired
    OwnerRepository OwnerRepositoryIT.ownerRepository;
    
    /**
     * This method will be automatically executed after each test method for freeing resources allocated with @Before annotated method.
     */
    @After
    public void OwnerRepositoryIT.clean() {
        
        // Clean needed after executing each test method
        // To be implemented by developer
        
    }
    
    /**
     * This method will be automatically executed before each test method for configuring needed resources.
     */
    @Before
    public void OwnerRepositoryIT.setup() {
        
        dod = new OwnerDataOnDemand(ownerRepository);
        
        // Setup needed before executing each test method
        // To be implemented by developer
        
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     */
    @Test
    @Ignore("To be implemented by developer")
    public void OwnerRepositoryIT.testFindAll() {
        
        // Setup
        // Implement additional setup if necessary
        
        // Exercise
        
        // Verify
        // Implement assertions
        
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     */
    @Test
    @Ignore("To be implemented by developer")
    public void OwnerRepositoryIT.testFindByFirstNameLike() {
        
        // Setup
        // Implement additional setup if necessary
        
        // Exercise
        
        // Verify
        // Implement assertions
        
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     */
    @Test
    @Ignore("To be implemented by developer")
    public void OwnerRepositoryIT.testCountByFirstNameLike() {
        
        // Setup
        // Implement additional setup if necessary
        
        // Exercise
        
        // Verify
        // Implement assertions
        
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     */
    @Test
    @Ignore("To be implemented by developer")
    public void OwnerRepositoryIT.testFindByCityLike() {
        
        // Setup
        // Implement additional setup if necessary
        
        // Exercise
        
        // Verify
        // Implement assertions
        
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     */
    @Test
    @Ignore("To be implemented by developer")
    public void OwnerRepositoryIT.testCountByCityLike() {
        
        // Setup
        // Implement additional setup if necessary
        
        // Exercise
        
        // Verify
        // Implement assertions
        
    }
    
}
